---
- hosts: all
  become: yes
  pre_tasks:
  - name: Installer les mises à jour
    tags: always
    package:
      #upgrade: dist
      update_cache: yes

- hosts: all
  become: yes
  roles:
    - base

- hosts: monitoring
  become: yes
  roles:
    - monitoring
