- name: Copier fichier HTML vers /tmp
  copy:
    src: "{{ default_html }}"
    dest: "{{ path_dest }}"
    owner: root
    group: root
    mode: 0644
  notify: stop_apache
- name: Stopper Apache
  tags: apache2
  service:
    name: apache2
    state: stopped
    enabled: no
  register: httpd
  when: ansible_distribution in ['Debian']
